//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME_INC_POE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_VC_PROG7311_188028607_Entities : DbContext
    {
        public DB_VC_PROG7311_188028607_Entities()
            : base("name=DB_VC_PROG7311_188028607_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CUST_ADDRESSES> TBL_CUST_ADDRESSES { get; set; }
        public virtual DbSet<TBL_CUSTOMER> TBL_CUSTOMER { get; set; }
        public virtual DbSet<TBL_CUSTOMER_PAYMENT_DETAILS> TBL_CUSTOMER_PAYMENT_DETAILS { get; set; }
        public virtual DbSet<TBL_EMPLOYEE> TBL_EMPLOYEE { get; set; }
        public virtual DbSet<TBL_PRODUCTS> TBL_PRODUCTS { get; set; }
        public virtual DbSet<TBL_PURCHASES> TBL_PURCHASES { get; set; }
    }
}
