//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME_INC_POE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CUSTOMER_PAYMENT_DETAILS
    {
        public string CUST_USERNAME { get; set; }
        public int CUST_CARD_NUMBER { get; set; }
        public int CUST_CVV { get; set; }
    
        public virtual TBL_CUSTOMER TBL_CUSTOMER { get; set; }
    }
}
