//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME_INC_POE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLOYEE
    {
        public string EMP_USERNAME { get; set; }
        public string EMP_PASSWORD { get; set; }
    }
}
