//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACME_INC_POE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CUSTOMER
    {
        public string CUST_USERNAME { get; set; }
        public string CUST_PASSWORD { get; set; }
    
        public virtual TBL_CUST_ADDRESSES TBL_CUST_ADDRESSES { get; set; }
        public virtual TBL_CUSTOMER_PAYMENT_DETAILS TBL_CUSTOMER_PAYMENT_DETAILS { get; set; }
        public virtual TBL_PURCHASES TBL_PURCHASES { get; set; }
    }
}
